### ISSUE TITLE
Not getting image for ENS values, it returns blockie icon

### ISSUE THREAD

**Issue by nikhilthakur001** [snapshot-labs/stamp#109]

**Comment by ChaituVR** [comment]
Hi @nikhilthakur001 Which URL you are trying?

**Comment by nikhilthakur001** [comment]
Hi @ChaituVR , plz try https://cdn.stamp.fyi/avatar/sriramkasyap.eth

**Comment by ChaituVR** [comment]
I think we don't support ENS from URL, it should be an address like https://cdn.stamp.fyi/avatar/0xc5911c67C92F79C76a6d47Ec02652C2e46457F32

**Comment by bonustrack** [comment]
> I think we don't support ENS from URL, it should be an address like https://cdn.stamp.fyi/avatar/0xc5911c67C92F79C76a6d47Ec02652C2e46457F32

We support ENS in address see: https://cdn.stamp.fyi/avatar/fabien.eth there must be an issue

**Comment by ChaituVR** [comment]
Looks like we don't support IPFS/eip155, For example:
```
ipfs://QmUNLeVojZczbJrUZbjqMpM32uGYbpJd1Auce8ahLapqef
eip155:1/erc1155:0xb32979486938aa9694bfc898f35dbed459f44424/10063
eip155:1/erc1155:0x495f947276749Ce646f68AC8c248420045cb7b5e/61751686310106735452369515624497384717106902022558848289817630643456812515329
```

But these URLs are somehow working maybe because of some cache 🤔 

https://cdn.stamp.fyi/avatar/0xc5911c67C92F79C76a6d47Ec02652C2e46457F32
https://cdn.stamp.fyi/avatar/fabien.eth

But not working in the Local, Looking into it

**Comment by ChaituVR** [comment]
So we should handle
- If input is address, lookup for its ENS name 
  `if(isAddress(name)) name = await provider.lookupAddress(name) || '';`-
- If avatar is IPFS, use IPFS to get image
- If avatars is like `eip155:1/erc1155:` call contract's `url` method
Problem with `eip155:1/erc1155:0x495f947276749Ce646f68AC8c248420045cb7b5e/61751686310106735452369515624497384717106902022558848289817630643456812515329` is it contains a URL from Opensea, example https://api.opensea.io/api/v1/metadata/0x495f947276749Ce646f68AC8c248420045cb7b5e/0x{id}
we need a API KEY to access this,
- Else easy way is using https://metadata.ens.domains/mainnet/avatar/fabien.eth?timestamp=1699294585751 but not sure if there is any rate-limit with this

**Comment by wa0x6e** [comment]
Same issue as here https://github.com/snapshot-labs/stamp/issues/76

**Comment by ChaituVR** [comment]
No there are multiple issues related https://github.com/snapshot-labs/stamp/issues/109#issuecomment-1798361605 , #76 is part of it, but I feel like using ENS metadata API like above is the best way, @wa0x6e @bonustrack you think we can use this?
