### ISSUE TITLE
feat: address resolver should return addresses in the input format

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/stamp#155]
Currently the address resolver API return object of addresses and names with addresses in the checksummed format. The issue is that it make harder on UI to use directly, it require mapping address manually because the input format is not the same as output. We should instead keep same format than the input addresses.

**Comment by ChaituVR** [comment]
Ideally, UI should send checksum format, and we should not only read addresses that are checksum

we made similar mistake of allowing any format of addresses  on score-api and it created lot of trouble, better to just accept checksum addresses

**Comment by wa0x6e** [comment]
enforcing checksum address will avoid all the address comparison with `.tolowercase()`.

But since we can not update some data in the database, it'll only works for future data, and code still should support non-checksumed address, so back to zero

**Comment by bonustrack** [comment]
We can always enforce a specific format for the cache, and it doesn't matter if we lose cache, isn't 1 day cache anyway? This would avoid running this logic: https://github.com/snapshot-labs/sx-ui/blob/9678fd774e01a092db44efe00c61324fb08ee1f8/src/helpers/stamp.ts#L12-L17 make much easier for anyone to integrate.
