### ISSUE TITLE
bug: ENS image is not showing up 

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/stamp#184]
I have many example of account with ENS domains like fireeyesdao.eth or griff.eth where avatar exist in ENS records but it's not showing up on Stamp, check here:
https://snapshotx.xyz/#/sn:0x0041ada9121061198b52ae28edeec8ace7c23f2ba8d66938c129af1a2245701c/delegates
https://app.ens.domains/fireeyesdao.eth
https://app.ens.domains/griff.eth
```[tasklist]
### Tasks
- [ ] https://github.com/snapshot-labs/stamp/pull/187
```

**Comment by wa0x6e** [comment]
Seems like `0x839395e20bbB182fa440d08F850E6c7A8f6F0780` is associated to `griff.eth`, but 

- https://stamp.fyi/avatar/griff.eth
- https://stamp.fyi/avatar/0x839395e20bbB182fa440d08F850E6c7A8f6F0780

Do not yield the same result.

Investigating ...
