### ISSUE TITLE
bug: fallback image returning default avatar for starknet

### ISSUE THREAD

**Issue by dschlabach** [snapshot-labs/stamp#216]
After #212, the fallback for addresses `0x...` always returns the default Starknet avatar instead of the jazzicon or blockie as was returned in the past.

I've also tried modifying our query with the `resolver` query param, but no luck so far.

`https://cdn.stamp.fyi/avatar/${address}?resolver=ens&fb=jazzicon&cb=40`

![image](https://github.com/snapshot-labs/stamp/assets/31226559/d48ea263-f7e5-442d-bf6e-a07abfcca478)

**Comment by wa0x6e** [comment]
Is it about an ETH address ro starknet address ?

**Comment by dschlabach** [comment]
any address using `0x...` 

e.g.

![CleanShot 2024-04-29 at 12 51 21](https://github.com/snapshot-labs/stamp/assets/31226559/1f93e0d0-3130-4a46-8886-875620e6f460)


https://snapshot.org/#/aave.eth/proposal/0x389b244cae117793a02673cf1600579b26ce409e3c25a2ea9bf5a5cc57d0a92d
