### ISSUE TITLE
chore: cover image are too heavy

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/stamp#243]
I can see cover image taking few seconds to load. Compared to Twitter cover image (having same size) it's about 4x more heavy on Stamp. Is there a way we can reduce the size without losing much on quality?

<img width="287" alt="image" src="https://github.com/snapshot-labs/stamp/assets/16245250/f7c3e508-7f37-4da5-936d-b48f11f74f60">

**Comment by wa0x6e** [comment]
We can test with nearlossless compression instead

**Comment by bonustrack** [comment]
Don't we do that already? But yes we can try

**Comment by bonustrack** [comment]
Currently with my internet it takes about 4sec for the cover image to appear

**Comment by Sekhmet** [comment]
`nearlossless` doesn't make great difference (142kB vs 166kB). Making it lossy with quality 80% gives us 17.7kB.
