### ISSUE TITLE
feat: Stamp should resolve user Snapshot profile name

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/stamp#260]
Currently Stamp name resolver only resolve domains like fabien.eth, it should also includes the profile name:
<img width="1469" alt="image" src="https://github.com/user-attachments/assets/55e2447c-d695-46f7-af21-2c8ed7595e23">

On the topnav we shouldn't query Snapshot hub to get profile name but only rely on Stamp to resolve name.
```[tasklist]
### Tasks
- [ ] https://github.com/snapshot-labs/stamp/pull/262
- [ ] https://github.com/snapshot-labs/snapshot-sequencer/pull/410
```

**Comment by wa0x6e** [comment]
What's the priority look like ? Always return snapshot first, or last ?

**Comment by ChaituVR** [comment]
Snapshot should be always first, then stamp
