### ISSUE TITLE
Unicode characters 504 Error

### ISSUE THREAD

**Issue by muratangin187** [snapshot-labs/stamp#29]
ENS: 😋😋😋.eth
Wallet Adress: 0x658ef498b52DEC8684Cf131e645Fe1e926690b37
504 PAGE:
https://cdn.stamp.fyi/avatar/😋😋😋.eth

But it exist in ens database:
https://app.ens.domains/name/😋😋😋.eth/details

Emojis are valid characters according to https://docs.ens.domains/frequently-asked-questions#what-about-foreign-characters-what-about-upper-case-letters-is-any-unicode-character-valid

**Comment by wa0x6e** [comment]
Should be working now
