### ISSUE TITLE
Load ENS avatar directly from onchain data

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/stamp#6]
Currently ENS avatar are loaded from ENS metadata server, it would resolve faster if we implement our own resolver that get avatar bases on onchain data

**Comment by ryanli-me** [comment]
what's the current perf of ENS metadata server vs our own resolver?

**Comment by bonustrack** [comment]
It will improve speed because we will load avatar directly without going through ENS metadata server, I'm not sure how much it will get improved I expect 30% faster, but even if its a little bit there is lot of optimization we could do later with that, we could detect when someone have updated his image or not have any image set. Here is some example code to resolve ENS image directly:
https://github.com/ensdomains/ens-metadata-service/blob/master/src/avatar.ts
https://github.com/metaphor-xyz/davatar-helpers/blob/master/packages/react/src/Image.tsx

**Comment by bonustrack** [comment]
@ryanli-me

**Comment by FlacoJones** [comment]
Relevant docs on fetching avatar uri from on-chain source: https://gist.github.com/Arachnid/9db60bd75277969ee1689c8742b75182

**Comment by ryanli-me** [comment]
Sorry this got lost. here's an on-chain resolution logic I did adapted from ether.js.

https://github.com/cyberconnecthq/cyberprofile/blob/main/utils/resolver.ts

**Comment by bonustrack** [comment]
Fixed in #12
